# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002840c40cd19e735c7119ebc7801a981b5dd2f0eac5e4ba4754060286bbaa35335c07138ff79fa7687ec124c42565df90d7fb4e073e251fe2cbc59090a42a12

test:
  secret_key_base: 83a187e3d595c3ad63151e5b135eb53f9fe56ff830086385b0c2ba951af4e4c26b73918cfb87041b95b70cb50ea038e486dcf8b9fe6f563ff5bf4483a2461a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
